#!/usr/bin/env bash
#
# Copyright 2014-2023 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# locate would be faster, but find is more universal
command -v find >/dev/null 2>&1 || exit 1

# try to render images to ascii art
command -v jp2a >/dev/null 2>&1 || exit 1

trap "pkill -f -9 lib/hollywood/ >/dev/null 2>&1; exit" INT
while true; do
	while read -r f; do
		clear
		jp2a --colors --term-fit "$f"
		sleep 0.57
	done < <(find -L /run/current-system/sw -maxdepth 6 -readable -size +0 -type f \
		-name '*.jpg' -or -name '*.png' -or -name '*.webp' | sort -R)
done
