#!/usr/bin/env bash
#
# Copyright 2014 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command -v ssh-keygen >/dev/null 2>&1 || exit 1
command -v ccze >/dev/null 2>&1 || exit 1

tmpfile="$(mktemp -t 'hollywood.XXXXXXXXXX')"
trap 'rm -f "$tmpfile"; pkill -f -9 lib/hollywood/' INT
while true; do
	echo y | ssh-keygen -vvv -b 1024 -t ed25519 -N "" -f "$tmpfile" | ccze -A -c default=red
	rm -f "$tmpfile" "$tmpfile.pub"
	sleep 3
done
